#!/usr/bin/env bash

set -eu

script_name="$(basename "$0")"

read -r -d '$' usage <<EOF
Usage:
  ${script_name} [--with-examples] [--debug]
  ${script_name} -h | --help

Options:
  -h --help        Show this screen.
  --with-examples  Build examples.
  --debug          Build examples using debug mode.
$
EOF

for opt in "${@:-}"; do
  case ${opt} in
    "") # Default; no options.
      ;;
    -h|--help)
      echo "${usage}"
      exit
      ;;
    --with-examples)
      WITH_EXAMPLES="on"
      shift
      ;;
    --debug)
      BUILD_TYPE="Debug"
      shift
      ;;
    *) # Unknown option...
      printf "${script_name}: invalid option -- '${opt//-/}'\n"
      echo "${usage}"
      exit 1
      ;;
  esac
done

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source_dir="$( dirname "${script_dir}" )"
build_dir="${source_dir}/build"

cmake -E make_directory "${build_dir}"
cmake -E chdir ${build_dir} cmake \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE:=Release}" \
  -DBUILD_EXAMPLES="${WITH_EXAMPLES:=off}" \
  "${source_dir}"
cmake --build "${build_dir}"
